// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trhctzzcrygadufhxeer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyaGN0enpjcnlnYWR1Zmh4ZWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MTc2NDcsImV4cCI6MjA2NzE5MzY0N30._yvDzjG83oY--unBcbW5TKMwy-hvSaZbrmGvSIftvns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});